# Generated by Django 3.2.12 on 2023-10-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcamimage',
            name='image',
            field=models.ImageField(upload_to='webcam_images/%Y/%m/%d/'),
        ),
    ]
